plugins {
    id 'com.android.application'
}

android {
    namespace 'com.titan.llama'
    compileSdk 35

    defaultConfig {
        applicationId 'com.titan.llama'
        minSdk 28
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['src/main/jniLibs']
        }
    }
}

dependencies {
}
