name: TITAN Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout TITAN
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android NDK
        uses: android-actions/setup-ndk@v3
        with:
          ndk-version: "27.2.12479018"

      - name: Check Android environment
        run: |
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME"
          echo "ANDROID_HOME=$ANDROID_HOME"
          cmake --version
          java -version
          adb version
